### ISSUE TITLE
assets:precompile error "is not yet checked out"

### ISSUE THREAD

**Issue by sbounmy** [ryanwi/rails7-on-docker#317]
Hello,

When deploying to render, I have the following issue :

```
18 [build 7/7] RUN ./bin/rails assets:precompile
Aug 27 08:04:17 AM  #18 0.224 /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/source/git.rb:221:in `rescue in load_spec_files': https://github.com/sequoia-gw/omniauth-notion.git is not yet checked out. Run `bundle install` first. (Bundler::GitError)
Aug 27 08:04:17 AM  #18 0.224   from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/source/git.rb:217:in `load_spec_files'
Aug 27 08:04:17 AM  #18 0.224   from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/source/path.rb:107:in `local_specs'
Aug 27 08:04:17 AM  #18 0.224   from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/source/git.rb:184:in `specs'
Aug 27 08:04:17 AM  #18 0.224   from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
```

Mostly coming from Dockerfile

`RUN ./bin/rails assets:precompile`

Gemfile :

`gem "omniauth-stripe-connect", github: "egeek/omniauth-stripe-connect"`

**Comment by sbounmy** [comment]
using Rails 7.0.6

**Comment by ryanwi** [comment]
@sbounmy try running locally `docker compose run --rm web bundle install` and see if that installs the gems your app is using that are not in this template. Does it update the `Gemfile.lock` after running that?

**Comment by sbounmy** [comment]
@ryanwi thanks ! I moved to docker but forgot how I fixed it. closing this :)
